# **************************************************************************
# Example 1:
# - rtl_syn:
#   - define:
#     - +define+UNIT_DELY
#   - incdir:
#     - hw/rtl/common_ip
#   - fileset: []
# Example 2:
# - rtl_syn:
#   - fileset:[]
#
# Note: If there is no 'define' or 'incdir' information,
# make sure no define or incdir line !
# **************************************************************************
- filelist:
  - crg:
    - hw/rtl/clk_rst_gen/clk_gen.v
    - hw/rtl/clk_rst_gen/rst_gen.v
    - hw/rtl/clk_rst_gen/crg.v
  - common_ip:
    - hw/rtl/common_ip/pulse_handshake.v
    - hw/rtl/common_ip/multi_handshake.v
    - hw/rtl/common_ip/synchronizer.v
    - hw/rtl/common_ip/jlsemi_util_async_reset_low_sync.v
    - hw/rtl/common_ip/jlsemi_util_sync_pos_with_rst_low.v
    - hw/rtl/common_ip/jlsemi_util_clkdiv_even_with_cfg.v
    - hw/rtl/common_ip/jlsemi_util_clkdiv_even_with_phase.v
    - hw/rtl/common_ip/jlsemi_util_clkgate.v
    - hw/rtl/common_ip/jlsemi_util_clkmux_sel1.v
    - hw/rtl/common_ip/jlsemi_util_clkbuf.v
    - hw/rtl/common_ip/jlsemi_util_and_cell.v
    - hw/rtl/common_ip/jlsemi_util_mux_cell.v
    - hw/rtl/common_ip/jlsemi_logic_cell.v
  - ctrl_sys:
    - hw/rtl/ctrl_sys/ctrl_sys.v
    - hw/rtl/ctrl_sys/cdc_500_200.v
  - mdio:
    - hw/rtl/ctrl_sys/mdio/mdio_top.v
    - hw/rtl/ctrl_sys/mdio/mdio_slave_45_backend.v
    - hw/rtl/ctrl_sys/mdio/watchdog_mdio.v
    - hw/rtl/ctrl_sys/mdio/mdio_slave_22_45_frontend_async.v
    - hw/rtl/ctrl_sys/mdio/mdio_slave_22_45_frontend_sync.v
    - hw/rtl/ctrl_sys/mdio/mdio_slave_22_backend.v
    - hw/rtl/ctrl_sys/mdio/cdc_1clk_signal.v
    - hw/rtl/ctrl_sys/mdio/cdc_200m_100m.v
    - hw/rtl/ctrl_sys/mdio/mdio_slave_22_45_backend.v
  - io_pad:
    - hw/rtl/top/iopad_top.v
    - hw/rtl/top/iopad_pdu_inst.v
    - hw/rtl/top/iopad_pdd_inst.v
  - pktctrl:
    - hw/rtl/pktctrl/pktctrl_top.v
    - hw/rtl/pktctrl/package_ctrl.v
    - hw/rtl/pktctrl/gen_write_logic.v
    - hw/rtl/pktctrl/gen_read_logic_mdio.v
    - hw/rtl/pktctrl/gen_read_logic_fast.v
    - hw/rtl/pktctrl/package_gen.v
    - hw/rtl/pktctrl/package_data_sel.v
    - hw/rtl/pktctrl/memory_wrapper.v
    - hw/rtl/pktctrl/memory_inst.v
  - top:
    - hw/rtl/analog/ANALOG_WRAPPER.sv
    - hw/rtl/top/analog_signal_mux.v
    - hw/rtl/top/DIGITAL_WRAPPER.v
    - hw/rtl/top/ASIC.v
  - dbg:
    - hw/rtl/dbg/dbg_top.v
    - hw/rtl/dbg/cap_src_gen.v
    - hw/rtl/dbg/dbg_core.v
    - hw/rtl/dbg/dbg_ram_1r1w_4096_wrapper.v
    - hw/rtl/dbg/ram_rd_ctrl.v
    - hw/rtl/dbg/bus_delay.v
    - hw/rtl/dbg/ram_wr_ctrl.v
    - hw/rtl/dbg/trigger.v
    - hw/rtl/dbg/stat_cnt.v
    - hw/rtl/dbg/match.v
    - hw/rtl/dbg/trigger_bit.v
    - hw/rtl/dbg/wr_addr_ctrl.v
  - regfile:
    - builds/verilog/top_regfile.v
  - ip_model:
    - /library/tsmc/cln28hpcp/IO/tphn28hpcpgv18_170a/Front_End/verilog/tphn28hpcpgv18_110a/tphn28hpcpgv18.v
    - /library/tsmc/cln28hpcp/STD/tcbn28hpcplusbwp40p140_180b/Front_End/verilog/tcbn28hpcplusbwp40p140_110a/tcbn28hpcplusbwp40p140.v
    - hw/library/ts1n28hpcpsvtb32768x36m16swso_180a/VERILOG/ts1n28hpcpsvtb32768x36m16swso_180a_ffg0p99v125c.v
  - simulation:
    - design_dv/tb/tb_ASIC.sv

- rtl_syn:
  - define:
    - +define+JL_SYNTHESIS
  - fileset: [crg, common_ip, ctrl_sys, mdio, io_pad, pktctrl, top, dbg, regfile]

- rtl_sim:
  - define:
    - +define+UNIT_DELY
  - fileset: [crg, common_ip, ctrl_sys, mdio, io_pad, pktctrl, top, dbg, regfile, ip_model, simulation]

- rtl_spyglass:
  - define:
    - +define+JL_SYNTHESIS
  - fileset: [crg, common_ip, ctrl_sys, mdio, io_pad, pktctrl, top, dbg, regfile]

- rtl_fpga:
  - define:
    - +define+FPGA
  - fileset: [crg, common_ip, ctrl_sys, mdio, io_pad, pktctrl, top, dbg, regfile]
